spring.application.name=11-saga-choreography-tenant-service

spring.rabbitmq.listener.simple.acknowledge-mode=manual

spring.datasource.url=jdbc:postgresql://localhost:5432/eda
spring.datasource.username=eda
spring.datasource.password=eda

eda.exchange=saga-exchange
eda.tenants.provisioned.routing-key=saga.tenant.provisioned
eda.billing.failed.queue=billing-failed-queue
eda.billing.failed.routing-key=saga.billing.failed
eda.billing.compensated.queue=billing-compensated-queue
eda.billing.compensated.routing-key=saga.billing.compensated
