spring.application.name=10-transactional-outbox

spring.datasource.url=jdbc:postgresql://localhost:5432/eda
spring.datasource.username=eda
spring.datasource.password=eda

spring.sql.init.mode=always

spring.rabbitmq.listener.simple.acknowledge-mode=manual