spring.application.name=08-delayed-retry

spring.rabbitmq.listener.simple.acknowledge-mode=manual

#spring.rabbitmq.listener.simple.retry.enabled=true
#spring.rabbitmq.listener.simple.retry.initial-interval=1000
#spring.rabbitmq.listener.simple.retry.multiplier=2
#spring.rabbitmq.listener.simple.retry.max-interval=20000
#spring.rabbitmq.listener.simple.retry.max-retries=3

