services:
  postgres:
    image: postgres:18-alpine
    container_name: task9-postgres
    environment:
      POSTGRES_DB: eda09
      POSTGRES_USER: eda
      POSTGRES_PASSWORD: eda
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: task9-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"